# Generated by Django 6.0.5 on 2026-06-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='custom_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userbook',
            name='custom_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/custom/'),
        ),
        migrations.AddField(
            model_name='userbook',
            name='custom_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
