"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from dotenv import load_dotenv

# This tells Django to look inside your secret .env file locally
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


### --- SECURITY SETTINGS --- ###
# We now pull these from Render's Environment Variables so hackers can't see them on GitHub.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure--n8ni-ylanm%l(f5=3j02e&1%$j^5sl5rgbum*%j0uz@3cwji#')

# Turns off the yellow error screens in production
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Tells Django which URLs are allowed to access this server
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Tells Django to trust form submissions coming from your Render/Custom URL
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost').split(',')

### --- PRODUCTION SECURITY HEADERS --- ###
# These only take effect when DEBUG=False (i.e., on Render).
if not DEBUG:
    # Tells Django it's behind Render's HTTPS reverse proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Forces all cookies to be sent over HTTPS only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Redirects any accidental HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True

    # Tells browsers to only connect via HTTPS for this many seconds
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
### ---------------------------------- ###


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'rest_framework',
    'books',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    ### --- WHITENOISE --- ###
    # This must be directly below SecurityMiddleware to serve your CSS/JS extremely fast.
    # WhiteNoise serves pre-collected static files from STATIC_ROOT in production.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    ### ------------------- ###
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

### --- DATABASE --- ###
# Connects to Render's PostgreSQL using the DATABASE_URL. 
# Falls back to SQLite locally if the URL isn't found.
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', f'sqlite:///{BASE_DIR}/db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}
### ---------------- ###


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==========================================================
# STATIC FILES (CSS, JavaScript, Images)
# ==========================================================

STATIC_URL = '/static/'

# This tells Django exactly where to pack all your files when Render runs collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The modern Django STORAGES dict (Django 4.2+)
# - "default" handles media files (user uploads → Cloudinary)
# - "staticfiles" handles CSS/JS/images (collected → served by WhiteNoise)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        # Uses Django's default storage to bypass the WhiteNoise
        # CompressedManifest race condition with Django admin files.
        # WhiteNoise middleware still serves from STATIC_ROOT efficiently.
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


# ==========================================================
# MEDIA FILES (User Uploads → Cloudinary)
# ==========================================================

# Cloudinary handles all media in production (ephemeral storage disappears on redeploy).
# MEDIA_URL and MEDIA_ROOT are only used locally for dev convenience.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# ==========================================================
# REST FRAMEWORK & JWT
# ==========================================================

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'